# Generated by Django 4.1.6 on 2023-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dailyjotter", "0007_author_about"),
    ]

    operations = [
        migrations.RemoveField(model_name="author", name="image",),
        migrations.RemoveField(model_name="post", name="image",),
        migrations.AddField(
            model_name="author",
            name="image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
